name: Build Documentation

on:
  push:
    branches:
      - master
    paths:
    - 'myPackage/**'

jobs:
  auto-doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Build doc
      run: |
        pip install pdoc3
        pdoc --html --config show_source_code=True --config show_type_annotations=True --config show_inherited_members=True --config git_link_template="'https://github.com/H4dr1en/ga-hello-world/blob/{commit}/{path}#L{start_line}-L{end_line}'" myPackage --force --output-dir docs
    - name: Push doc
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git remote add github "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        git pull github ${{ github.ref }} --ff-only
        git add -f -A ./docs/*
        git commit -m "Update documentation"
        git push github HEAD:${{ github.ref }}