name: Continuous Integration

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'myPackage/**'
  push:
    branches:
      - dev
    paths:
      - 'myPackage/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Lint with flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        flake8 . --count --show-source --statistics --max-line-length=127
    - name: Install deps and engine
      if: always()
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .
    - name: Test with pytest
      run: |
        pip install pytest
        pytest